// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessagesOutput = { messages: Array<string>, last: string | null, count: number, };
