// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthenticateParams } from "./Params";
import type { EchoParams } from "./Params";
import type { EmptyParams } from "../Nitram";

export type AuthenticateAPI = { i: AuthenticateParams, o: boolean, };

export type EchoAPI = { i: EchoParams, o: string, };

export type HelloAPI = { i: EmptyParams, o: string, };
