// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthenticateParams = { token: string, };

export type GetTokenParams = { user_name: string, };

export type SendMessageParams = { message: string, };
