// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetTokenParams = { user_name: string, };

export type MessagesParams = { channel: string, };

export type SendMessageParams = { message: string, channel: string, };
